
# Set up

Load packages
```{r}
library(tidyverse)
library(sf)
library(tmap)
library(rnaturalearth)
library(terra)
```

Settings and universal variables
```{r}
tmap_mode(mode = "view")

crs = 3857 # WGS 84 / Pseudo-Mercator (projected)

options(scipen=999)
```

# Import data

## Covariates

Road density
```{r}
road_density = rast("Raw data/Covariates/Road access/GRIP4_density_total/grip4_total_dens_m_km2.asc")
```
Distance to water
```{r}
dist_to_water = rast("Raw data/Covariates/Distance to water/distance_to_water.tif")
```

Nightlights
```{r}
nightlights = rast("Raw data/Covariates/Nightlights/VNL_npp_2024_global_vcmslcfg_v2_c202502261200.average_masked.dat.tif/VNL_npp_2024_global_vcmslcfg_v2_c202502261200.average_masked.dat.tif")
```

Protected areas
```{r}
protected_areas = st_read("Raw data/Covariates/Protected areas/WDPA_WDOECM_May2025_Public_all/WDPA_WDOECM_May2025_Public_all.gdb", layer = "WDPA_WDOECM_poly_May2025_all")
```

Land cover
```{r}
land_cover = rast("Raw data/Covariates/Land cover/MCD12C1.A2023001.061.2024251212901.hdf")
```

Population Density
```{r}
pop_dens = rast("Raw data/Covariates/Population density/gpw_v4_population_density_rev11_2020_30_sec_2020.tif")
```


