
# Import packages
```{r}
library(sf)          # for vector data
library(terra)       # for raster data
library(exactextractr) # for fast extraction
library(ggplot2)     # for visualization
library(dplyr)       # for data wrangling
library(rnaturalearth)
library(tmap)
library(leaflet)
```

```{r}
crs = 32721
rast_crs = paste("EPSG:", crs, sep = "")

tmap_mode("view")
```


# Import data
```{r}
bolivia = st_transform(ne_countries(country = "Bolivia", scale = "medium", returnclass = "sf"), crs)%>%vect()

road_vector = st_transform(st_read("Raw data/Covariates/Road access/OSM Bolivia (test)/gis_osm_roads_free_1.shp"), crs)

#road_v_sa = st_transform(st_read("Raw data/Covariates/Road access/GRIP4_Region2_vector_shp/GRIP4_region2.shp"), crs)%>%
  #st_filter(., bolivia, .pred = st_intersects())

road_density_raster = rast("Raw data/Covariates/Road access/GRIP4_density_total/grip4_total_dens_m_km2.asc")%>%
  project(rast_crs)%>%
  crop(bolivia)%>%
  mask(bolivia)

# 2. Create binary road mask (1=road, NA=no road)
road_mask <- classify(road_density_raster, 
                     rcl = matrix(c(0, NA, 
                                   0.0001, Inf, 1), 
                                 ncol = 2, byrow = TRUE), 
                     right = FALSE)
                     
distance_raster_mask <- distance(road_mask)%>%
  mask(bolivia)
```


# Calculating distance to roads

## Distance to roads function
```{r}
create_distance_to_roads_raster = function(roads, 
                                         road_density) {

  # Create a blank raster with the same properties as road density
  template = rast(road_mask)
  
  # Rasterize the roads (1 for roads, NA for non-roads)
  road_raster <- rasterize(roads, template, field=1, background=NA)
  
  # Calculate distance to nearest road (in meters if CRS is projected)
  distance_raster = distance(road_raster)%>%
    mask(bolivia)
  
  return(distance_raster)}
```

## Implementing
```{r}
# Generate the distance raster
distance_raster = create_distance_to_roads_raster(road_vector, road_density_raster)
```

# Map Comparison
```{r}
my_breaks <- c(0, 10000, 20000, 30000, 40000, 50000)

tm_shape(distance_raster)+
  tm_raster(style = "fixed", breaks = my_breaks)+
  tm_shape(distance_raster_mask) +
  tm_raster(style = "fixed", breaks = my_breaks)


pal <- colorBin(
  palette = c("#2b83ba", "#80bfac", "#d5eea0", "#ffffbf", 
              "#fdc980", "#f88d51", "#d7191c"),
  domain = my_breaks,
  bins = my_breaks,
  na.color = "transparent"
)

leaflet() %>%
  addTiles() %>%
  addRasterImage(distance_raster, color = pal, group = "'True' Distance") %>%
  addRasterImage(distance_raster_mask, color = pal, group = "Distance Derived from Density") %>%
  addLegend(pal = pal, values = values(distance_raster), title = "Distance", position = "bottomright")%>%
  addLayersControl(
    overlayGroups = c("'True' Distance", "Distance Derived from Density"),
    options = layersControlOptions(collapsed = FALSE))

tm_shape(road_density_raster)+
  tm_raster(style = "fisher")

diff_raster <- distance_raster - distance_raster_mask
plot(diff_raster, main = "Error in Approximation (m)")
```
```{r}
# Create sample points for validation (10,000 stratified random points)
set.seed(123)

vals <- spatSample(c(distance_raster, distance_raster_mask), 10000, method="random")
vals <- na.omit(vals)

cor(vals[,1], vals[,2])^2
```




